import { defineConfig } from 'tinacms';

const branch =
  process.env.NEXT_PUBLIC_TINA_BRANCH ||
  process.env.CF_PAGES_BRANCH ||
  process.env.HEAD ||
  'main';

const textArea = {
  component: 'textarea',
} as const;

const headingFields = [
  { type: 'string', name: 'eyebrow', label: 'Kleine Überschrift' },
  { type: 'string', name: 'title', label: 'Titel', ui: textArea },
  { type: 'string', name: 'text', label: 'Text', ui: textArea },
] as any;

const simpleTextFields = [
  { type: 'string', name: 'label', label: 'Beschriftung' },
  { type: 'string', name: 'placeholder', label: 'Platzhalter' },
] as any;

export default defineConfig({
  branch,
  clientId: process.env.NEXT_PUBLIC_TINA_CLIENT_ID,
  token: process.env.TINA_TOKEN,
  build: {
    outputFolder: 'admin',
    publicFolder: 'public',
  },
  media: {
    tina: {
      mediaRoot: '',
      publicFolder: 'public',
    },
  },
  schema: {
    collections: [
      {
        name: 'siteContent',
        label: 'Website Inhalte',
        path: 'content',
        format: 'json',
        match: {
          include: 'site',
        },
        ui: {
          allowedActions: {
            create: false,
            delete: false,
          },
        },
        fields: [
          {
            type: 'object',
            name: 'site',
            label: 'Grunddaten & Kontakt',
            fields: [
              { type: 'string', name: 'name', label: 'Name der Grillhütte' },
              { type: 'string', name: 'shortName', label: 'Kurzname' },
              { type: 'string', name: 'logoText', label: 'Logo-Kürzel im Header' },
              { type: 'string', name: 'location', label: 'Ort / Lage' },
              { type: 'string', name: 'address', label: 'Adresse / Treffpunkt', ui: textArea },
              { type: 'string', name: 'claim', label: 'Haupt-Claim' },
              { type: 'string', name: 'subclaim', label: 'Hero-Untertitel', ui: textArea },
              { type: 'string', name: 'description', label: 'Beschreibung', ui: textArea },
              { type: 'string', name: 'phone', label: 'Telefonnummer Linkformat' },
              { type: 'string', name: 'whatsappNumber', label: 'WhatsApp Nummer ohne Plus' },
              { type: 'string', name: 'phoneDisplay', label: 'Telefon Anzeige' },
              { type: 'string', name: 'email', label: 'E-Mail' },
              { type: 'string', name: 'facebookUrl', label: 'Facebook URL' },
              { type: 'string', name: 'price', label: 'Preis' },
              { type: 'string', name: 'contactTimes', label: 'Kontaktzeiten', list: true },
              { type: 'string', name: 'googleCalendarSrc', label: 'Google Kalender Embed URL', ui: textArea },
            ],
          },
          {
            type: 'object',
            name: 'meta',
            label: 'SEO & Vorschau',
            fields: [
              { type: 'string', name: 'metadataBase', label: 'Website-URL' },
              { type: 'string', name: 'titleSuffix', label: 'Seitentitel Zusatz' },
              { type: 'string', name: 'description', label: 'SEO Beschreibung', ui: textArea },
              { type: 'string', name: 'keywords', label: 'Keywords', list: true },
              { type: 'string', name: 'openGraphDescription', label: 'Social-Media Beschreibung', ui: textArea },
              { type: 'image', name: 'openGraphImage', label: 'Social-Media Bild' },
              { type: 'string', name: 'openGraphImageAlt', label: 'Alt-Text Social-Media Bild' },
              { type: 'string', name: 'locale', label: 'Locale' },
            ],
          },
          {
            type: 'object',
            name: 'hero',
            label: 'Startbereich / Hero',
            fields: [
              { type: 'image', name: 'image', label: 'Hero-Bild' },
              { type: 'image', name: 'imageWebp', label: 'Hero-Bild WebP optional' },
              { type: 'string', name: 'imageAlt', label: 'Alt-Text Hero-Bild' },
              { type: 'string', name: 'priceSuffix', label: 'Preis-Zusatz im Badge' },
              { type: 'string', name: 'titleLine1', label: 'Titel Zeile 1' },
              { type: 'string', name: 'titleLine2', label: 'Titel Zeile 2' },
              { type: 'string', name: 'cardKicker', label: 'Info-Karte kleine Überschrift' },
              { type: 'string', name: 'cardTitle', label: 'Info-Karte Titel', ui: textArea },
              { type: 'string', name: 'cardText', label: 'Info-Karte Text', ui: textArea },
            ],
          },
          {
            type: 'object',
            name: 'ui',
            label: 'Buttons & kurze UI-Texte',
            fields: [
              { type: 'string', name: 'headerWhatsapp', label: 'Header WhatsApp' },
              { type: 'string', name: 'headerInquiry', label: 'Header Anfrage' },
              { type: 'string', name: 'heroPrimaryButton', label: 'Hero Hauptbutton' },
              { type: 'string', name: 'heroWhatsappButton', label: 'Hero WhatsApp Button' },
              { type: 'string', name: 'heroGalleryButton', label: 'Hero Galerie Button' },
              { type: 'string', name: 'galleryInquiryButton', label: 'Galerie Anfrage Button' },
              { type: 'string', name: 'requiredLabel', label: 'Pflichtfeld Label' },
              { type: 'string', name: 'faqOpenIcon', label: 'FAQ Öffnen Icon' },
              { type: 'string', name: 'mobileCall', label: 'Mobile Bar Anrufen' },
              { type: 'string', name: 'mobileInquiry', label: 'Mobile Bar Anfrage' },
              { type: 'string', name: 'mobileWhatsapp', label: 'Mobile Bar WhatsApp' },
            ],
          },
          {
            type: 'object',
            name: 'navItems',
            label: 'Navigation',
            list: true,
            fields: [
              { type: 'string', name: 'href', label: 'Linkziel' },
              { type: 'string', name: 'label', label: 'Beschriftung' },
            ],
          },
          {
            type: 'object',
            name: 'trustItems',
            label: 'Vertrauensleiste unter Hero',
            list: true,
            fields: [
              { type: 'string', name: 'icon', label: 'Icon / Emoji' },
              { type: 'string', name: 'title', label: 'Titel' },
              { type: 'string', name: 'text', label: 'Text' },
            ],
          },
          {
            type: 'object',
            name: 'sections',
            label: 'Abschnittsüberschriften',
            fields: [
              { type: 'object', name: 'experience', label: 'Erlebnis', fields: headingFields },
              { type: 'object', name: 'gallery', label: 'Galerie', fields: headingFields },
              { type: 'object', name: 'features', label: 'Ausstattung', fields: headingFields },
              { type: 'object', name: 'inquiry', label: 'Kalender & Anfrage', fields: headingFields },
              { type: 'object', name: 'guestbook', label: 'Gästebuch', fields: headingFields },
              { type: 'object', name: 'faq', label: 'FAQ', fields: headingFields },
              { type: 'object', name: 'contact', label: 'Kontakt', fields: headingFields },
            ],
          },
          {
            type: 'object',
            name: 'heroStats',
            label: 'Hero Kennzahlen',
            list: true,
            fields: [
              { type: 'string', name: 'value', label: 'Wert' },
              { type: 'string', name: 'label', label: 'Titel' },
              { type: 'string', name: 'note', label: 'Hinweis' },
            ],
          },
          {
            type: 'object',
            name: 'moments',
            label: 'Erlebnis-Karten',
            list: true,
            fields: [
              { type: 'string', name: 'kicker', label: 'Kleine Überschrift' },
              { type: 'string', name: 'title', label: 'Titel' },
              { type: 'string', name: 'text', label: 'Text', ui: textArea },
            ],
          },
          {
            type: 'object',
            name: 'features',
            label: 'Ausstattung',
            list: true,
            fields: [
              { type: 'string', name: 'icon', label: 'Icon / Emoji' },
              { type: 'string', name: 'title', label: 'Titel' },
              { type: 'string', name: 'text', label: 'Text', ui: textArea },
            ],
          },
          {
            type: 'object',
            name: 'galleryImages',
            label: 'Galerie',
            list: true,
            fields: [
              { type: 'image', name: 'src', label: 'Bild' },
              { type: 'string', name: 'title', label: 'Titel' },
              { type: 'string', name: 'alt', label: 'Alt-Text für Barrierefreiheit' },
              { type: 'string', name: 'text', label: 'Beschreibung', ui: textArea },
            ],
          },
          {
            type: 'object',
            name: 'mapSection',
            label: 'Anfahrt / Google Maps',
            fields: [
              { type: 'boolean', name: 'enabled', label: 'Anfahrtsbereich anzeigen' },
              { type: 'string', name: 'eyebrow', label: 'Kleine Überschrift' },
              { type: 'string', name: 'title', label: 'Titel', ui: textArea },
              { type: 'string', name: 'text', label: 'Text', ui: textArea },
              { type: 'string', name: 'addressLabel', label: 'Adress-Label' },
              { type: 'string', name: 'address', label: 'Adresse', ui: textArea },
              { type: 'string', name: 'parkingTitle', label: 'Parken Titel' },
              { type: 'string', name: 'parkingNote', label: 'Parkhinweis', ui: textArea },
              { type: 'string', name: 'accessTitle', label: 'Zufahrt Titel' },
              { type: 'string', name: 'accessNote', label: 'Zufahrtshinweis', ui: textArea },
              { type: 'string', name: 'mapLink', label: 'Google Maps Link', ui: textArea },
              { type: 'string', name: 'mapButtonLabel', label: 'Maps Button' },
              { type: 'string', name: 'embedSrc', label: 'Google Maps Embed src', ui: textArea },
              { type: 'string', name: 'iframeTitle', label: 'Karten Titel' },
              { type: 'string', name: 'placeholderTitle', label: 'Platzhalter Titel' },
              { type: 'string', name: 'placeholderText', label: 'Platzhalter Text', ui: textArea },
            ],
          },
          {
            type: 'object',
            name: 'processSteps',
            label: 'Anfrage Ablauf',
            list: true,
            fields: [
              { type: 'string', name: 'number', label: 'Nummer' },
              { type: 'string', name: 'title', label: 'Titel' },
              { type: 'string', name: 'text', label: 'Text', ui: textArea },
            ],
          },
          {
            type: 'object',
            name: 'inquiryContent',
            label: 'Anfrageformular & Kalender',
            fields: [
              { type: 'string', name: 'emailSubject', label: 'E-Mail Betreff' },
              { type: 'string', name: 'calendarKicker', label: 'Kalender kleine Überschrift' },
              { type: 'string', name: 'calendarTitle', label: 'Kalender Titel' },
              { type: 'string', name: 'calendarButton', label: 'Kalender Button' },
              { type: 'string', name: 'calendarIframeTitle', label: 'Kalender Iframe Titel' },
              { type: 'string', name: 'calendarMobileIcon', label: 'Kalender Mobile Icon' },
              { type: 'string', name: 'calendarMobileTitle', label: 'Kalender Mobile Titel' },
              { type: 'string', name: 'calendarMobileText', label: 'Kalender Mobile Text', ui: textArea },
              { type: 'string', name: 'calendarMobileButton', label: 'Kalender Mobile Button' },
              { type: 'string', name: 'formKicker', label: 'Formular kleine Überschrift' },
              { type: 'string', name: 'formTitle', label: 'Formular Titel' },
              { type: 'string', name: 'formText', label: 'Formular Text', ui: textArea },
              { type: 'string', name: 'progressTitle', label: 'Fortschritt Titel' },
              { type: 'string', name: 'progressSuffix', label: 'Fortschritt Zusatz' },
              { type: 'string', name: 'requiredHint', label: 'Hinweis bei fehlenden Pflichtfeldern', ui: textArea },
              { type: 'string', name: 'whatsappButton', label: 'WhatsApp Button' },
              { type: 'string', name: 'emailButton', label: 'E-Mail Button' },
              { type: 'string', name: 'previewSummary', label: 'Nachrichtenvorschau Text' },
              { type: 'string', name: 'messageIntro', label: 'Nachrichten-Intro', ui: textArea },
              {
                type: 'object',
                name: 'fields',
                label: 'Formularfelder',
                fields: [
                  { type: 'object', name: 'name', label: 'Name', fields: simpleTextFields },
                  { type: 'object', name: 'phone', label: 'Telefon', fields: simpleTextFields },
                  { type: 'object', name: 'email', label: 'E-Mail', fields: simpleTextFields },
                  { type: 'object', name: 'date', label: 'Wunschtermin', fields: simpleTextFields },
                  { type: 'object', name: 'time', label: 'Zeitraum / Uhrzeit', fields: simpleTextFields },
                  { type: 'object', name: 'people', label: 'Personenzahl', fields: simpleTextFields },
                  { type: 'object', name: 'occasion', label: 'Anlass', fields: simpleTextFields },
                  { type: 'object', name: 'message', label: 'Nachricht', fields: simpleTextFields },
                ],
              },
              {
                type: 'object',
                name: 'messageLabels',
                label: 'Labels in der vorbereiteten Nachricht',
                fields: [
                  { type: 'string', name: 'name', label: 'Name' },
                  { type: 'string', name: 'phone', label: 'Telefon' },
                  { type: 'string', name: 'email', label: 'E-Mail' },
                  { type: 'string', name: 'date', label: 'Wunschtermin' },
                  { type: 'string', name: 'time', label: 'Zeitraum / Uhrzeit' },
                  { type: 'string', name: 'people', label: 'Personenzahl' },
                  { type: 'string', name: 'occasion', label: 'Anlass' },
                  { type: 'string', name: 'message', label: 'Nachricht' },
                ],
              },
            ],
          },
          {
            type: 'object',
            name: 'guestbookSamples',
            label: 'Gästebuch Beispiel-Einträge',
            list: true,
            fields: [
              { type: 'string', name: 'id', label: 'ID' },
              { type: 'string', name: 'name', label: 'Name' },
              { type: 'string', name: 'date', label: 'Datum / Anlass' },
              { type: 'string', name: 'message', label: 'Nachricht', ui: textArea },
            ],
          },
          {
            type: 'object',
            name: 'guestbookContent',
            label: 'Gästebuch Oberfläche',
            fields: [
              { type: 'string', name: 'nameLabel', label: 'Name Label' },
              { type: 'string', name: 'namePlaceholder', label: 'Name Platzhalter' },
              { type: 'string', name: 'messageLabel', label: 'Nachricht Label' },
              { type: 'string', name: 'messagePlaceholder', label: 'Nachricht Platzhalter' },
              { type: 'string', name: 'submitButton', label: 'Absenden Button' },
              { type: 'string', name: 'moderationHint', label: 'Moderationshinweis', ui: textArea },
              { type: 'string', name: 'validationMessage', label: 'Fehlermeldung' },
              { type: 'string', name: 'successMessage', label: 'Erfolgsmeldung', ui: textArea },
              { type: 'string', name: 'planKicker', label: 'Plan kleine Überschrift' },
              { type: 'string', name: 'planTitle', label: 'Plan Titel' },
              { type: 'string', name: 'planText', label: 'Plan Text', ui: textArea },
              { type: 'string', name: 'stars', label: 'Sterne' },
              { type: 'string', name: 'localLabel', label: 'Lokal Label' },
              { type: 'string', name: 'quoteOpen', label: 'Anführungszeichen Anfang' },
              { type: 'string', name: 'quoteClose', label: 'Anführungszeichen Ende' },
            ],
          },
          {
            type: 'object',
            name: 'faqs',
            label: 'FAQ',
            list: true,
            fields: [
              { type: 'string', name: 'question', label: 'Frage' },
              { type: 'string', name: 'answer', label: 'Antwort', ui: textArea },
            ],
          },
          {
            type: 'object',
            name: 'contactContent',
            label: 'Kontaktbereich',
            fields: [
              { type: 'string', name: 'callLabel', label: 'Anruf Label' },
              { type: 'string', name: 'whatsappLabel', label: 'WhatsApp Label' },
              { type: 'string', name: 'whatsappValue', label: 'WhatsApp Wert' },
              { type: 'string', name: 'emailLabel', label: 'E-Mail Label' },
              { type: 'string', name: 'hoursTitle', label: 'Erreichbarkeit Titel' },
              { type: 'string', name: 'hoursText', label: 'Erreichbarkeit Text', ui: textArea },
              { type: 'string', name: 'fastTitle', label: 'Schnellster Weg Titel' },
              { type: 'string', name: 'fastInquiryLabel', label: 'Anfrage Button' },
              { type: 'string', name: 'fastWhatsappLabel', label: 'WhatsApp Button' },
              { type: 'string', name: 'fastFacebookLabel', label: 'Facebook Button' },
              { type: 'string', name: 'fastText', label: 'Schnellster Weg Text', ui: textArea },
            ],
          },
          {
            type: 'object',
            name: 'footerContent',
            label: 'Footer',
            fields: [
              { type: 'string', name: 'copyrightPrefix', label: 'Copyright Zeichen/Text' },
              { type: 'string', name: 'facebookLabel', label: 'Facebook Label' },
              { type: 'string', name: 'impressumLabel', label: 'Impressum Label' },
              { type: 'string', name: 'datenschutzLabel', label: 'Datenschutz Label' },
            ],
          },
          {
            type: 'object',
            name: 'legal',
            label: 'Impressum & Datenschutz',
            fields: [
              { type: 'string', name: 'backLabel', label: 'Zurück-Link' },
              {
                type: 'object',
                name: 'impressum',
                label: 'Impressum',
                fields: [
                  { type: 'string', name: 'title', label: 'Titel' },
                  { type: 'string', name: 'intro', label: 'Einleitung', ui: textArea },
                  {
                    type: 'object',
                    name: 'sections',
                    label: 'Abschnitte',
                    list: true,
                    fields: [
                      { type: 'string', name: 'title', label: 'Titel' },
                      { type: 'string', name: 'text', label: 'Text', ui: textArea },
                    ],
                  },
                ],
              },
              {
                type: 'object',
                name: 'datenschutz',
                label: 'Datenschutz',
                fields: [
                  { type: 'string', name: 'title', label: 'Titel' },
                  { type: 'string', name: 'intro', label: 'Einleitung', ui: textArea },
                  {
                    type: 'object',
                    name: 'sections',
                    label: 'Abschnitte',
                    list: true,
                    fields: [
                      { type: 'string', name: 'title', label: 'Titel' },
                      { type: 'string', name: 'text', label: 'Text', ui: textArea },
                    ],
                  },
                ],
              },
            ],
          },
        ],
      },
    ],
  },
});
